{
    "name": "Collection Points",
    "version": "0.0",
    "category": "Operations/Environment",
    "license": "AGPL-3",
    "summary": "Management features for collection points",
    "author": "Henrique Espadas",
    "website": "henriqueep@hotmail.com",
    "depends": ["map_localization", "website"],
    "data": [
        "security/ir.model.access.csv",
        "security/groups.xml",
        "views/assets.xml",
        "views/collection_point_views.xml",
        "views/waste_type_views.xml",
        "views/menus.xml",
        "static/src/xml/find_recycling_points_template.xml",
    ],
    "installable": True,
    "application": True,
    "auto_install": False,
}
